In [3]:
#Conda env: py_3916

#Import packages
#---------------------------------------
import sys
from matplotlib import pyplot as plt
import numpy as np
import json
import pandas as pd
import seaborn as sns


#Import your modules
#---------------------------------------
import plaque_f as pf

# Define paths
#----------------------------------------------------------------------
l_code = '/Users/dominicburrows/Dropbox/PhD/Analysis/my_scripts/GitHub/'
l_data = '/Users/dominicburrows/Dropbox/PhD/analysis/Project/'
l_fig = '/Users/dominicburrows/Dropbox/PhD/figures/'

s_code = '/cndd3/dburrows/CODE/'
s_data = '/cndd3/dburrows/DATA/'
s_fig = '/cndd3/dburrows/FIGS/'

%load_ext autoreload
sys.version

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


'3.9.16 (main, Jan 11 2023, 16:05:54) \n[GCC 11.2.0]'

# Load data

In [2]:
def run_(name):
    # Declare paths
    data_path = s_data + 'spatial_transcriptomics/plaques/' + name + '.json'
    coord_path = '/cndd2/agelber/hal/qc_aligned/' + name + '/outs/spatial/tissue_positions.csv'
    genes_path = '/cndd2/agelber/hal/qc_aligned/' + name + '/outs/filtered_feature_bc_matrix.h5'
    meta = pd.read_csv('/cndd3/dburrows/DATA/spatial_transcriptomics/plaques/allspots_meta.csv') #FILTERED
    meta_filt = meta[meta['sample'] == name]

    spot_df, gene_df = pf.sort_data(data_path, coord_path, genes_path, 
                                    meta_filt, min_cell_per_gene=100, norm_factor=1e6)
    
    #Sanity check
    assert spot_df.shape[0] == gene_df.shape[0] == meta_filt.shape[0]
    assert 'Thy1' not in gene_df.columns.values or 'humanAPP' not in gene_df.columns.values
    print('Number of spots: ' + str(gene_df.shape[0]))
    print('Number of genes: ' + str(gene_df.shape[1]))
    return(spot_df, gene_df)

In [380]:
name = '030-D'
spot_df, gene_df = run_(name)

/home/dburrows/anaconda3/envs/py_3916/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/dburrows/anaconda3/envs/py_3916/lib/python3.9/site-packages/scanpy/preprocessing/_normalization.py:197: UserWarning: Some cells have zero counts
  warn(UserWarning('Some cells have zero counts'))


Number of spots: 3382
Number of genes: 13185


In [382]:
spot_df
gene_df

Sox17     Mrpl15      Lypla1       Tcea1       Rgs20  \
AAACAAGTATCTCCCA-1  214.9151   0.000000    0.000000   71.638367  214.915100   
AAACAATCTACTAGCA-1    0.0000   0.000000    0.000000    0.000000    0.000000   
AAACAGAGCGACTCCT-1    0.0000   0.000000    0.000000    0.000000    0.000000   
AAACAGTGTTCCTGGG-1    0.0000   0.000000   35.880875    0.000000   35.880875   
AAACATTTCCCGGATT-1    0.0000  96.547470   38.618988   57.928482   19.309494   
...                      ...        ...         ...         ...         ...   
TTGTTTCACATCCAGG-1    0.0000  73.686539   36.843269  110.529808   36.843269   
TTGTTTCATTAGTCTA-1    0.0000   0.000000   38.908993   38.908993   77.817986   
TTGTTTCCATACAACT-1    0.0000  68.189560  113.649277   45.459709   22.729855   
TTGTTTGTATTACACG-1    0.0000   0.000000    0.000000   58.414627    0.000000   
TTGTTTGTGTAAATTC-1    0.0000   0.000000    0.000000    0.000000    0.000000   

                       Atp6v1h      Oprk1     Rb1cc1        St18      Pcmtd1  \
AAACAAGTATCTCCCA-1  429.830200   0.000000   0.000000    0.000000   71.638367   
AAACAATCTACTAGCA-1  158.906723   0.000000   0.000000  317.813446  158.906723   
AAACAGAGCGACTCCT-1  235.478806   0.000000   0.000000    0.000000    0.000000   
AAACAGTGTTCCTGGG-1  215.285248   0.000000  35.880875    0.000000  143.523499   
AAACATTTCCCGGATT-1  193.094940  19.309494  96.547470    0.000000  154.475952   
...                        ...        ...        ...         ...         ...   
TTGTTTCACATCCAGG-1  257.902893   0.000000   0.000000    0.000000   73.686539   
TTGTTTCATTAGTCTA-1  194.544968   0.000000   0.000000    0.000000  116.726974   
TTGTTTCCATACAACT-1  113.649277  22.729855  90.919418    0.000000   68.189560   
TTGTTTGTATTACACG-1  175.243881   0.000000   0.000000    0.000000  175.243881   
TTGTTTGTGTAAATTC-1    0.000000   0.000000   0.000000    0.000000  121.506683   

                    ...      mt-Nd4l        mt-Nd4       mt-Nd5      mt-Nd6  \
AAACAAGTATCTCCCA-1  ...   573.106934  18984.167969  3008.811523   71.638367   
AAACAATCTACTAGCA-1  ...   158.906723   8422.056641  1271.253784  158.906723   
AAACAGAGCGACTCCT-1  ...  1255.886963  28492.935547  2747.252686  235.478806   
AAACAGTGTTCCTGGG-1  ...   502.332245  19949.765625  2870.469971   35.880875   
AAACATTTCCCGGATT-1  ...    77.237976   4383.255371   617.903809   38.618988   
...                 ...          ...           ...          ...         ...   
TTGTTTCACATCCAGG-1  ...   184.216339   8916.071289  1289.514404   73.686539   
TTGTTTCATTAGTCTA-1  ...   194.544968  10855.609375  1283.996704   38.908993   
TTGTTTCCATACAACT-1  ...   204.568695  11637.685547  1545.630127   22.729855   
TTGTTTGTATTACACG-1  ...   700.975525  24183.656250  3329.633789  116.829254   
TTGTTTGTGTAAATTC-1  ...  1215.066895  24665.857422  2308.626953    0.000000   

                         mt-Cytb  CAAA01118383.1      Vamp7      Spry3  \
AAACAAGTATCTCCCA-1  22924.277344             0.0   0.000000   0.000000   
AAACAATCTACTAGCA-1  12076.911133             0.0   0.000000   0.000000   
AAACAGAGCGACTCCT-1  30847.722656             0.0   0.000000   0.000000   
AAACAGTGTTCCTGGG-1  20452.097656             0.0  35.880875  35.880875   
AAACATTTCCCGGATT-1   6082.490723             0.0  77.237976  19.309494   
...                          ...             ...        ...        ...   
TTGTTTCACATCCAGG-1  12931.987305             0.0  36.843269   0.000000   
TTGTTTCATTAGTCTA-1  12606.513672             0.0  38.908993   0.000000   
TTGTTTCCATACAACT-1  14319.808594             0.0  45.459709   0.000000   
TTGTTTGTATTACACG-1  24358.900391             0.0   0.000000   0.000000   
TTGTTTGTGTAAATTC-1  28554.070312             0.0   0.000000   0.000000   

                        Tmlhe  AC149090.1  
AAACAAGTATCTCCCA-1   0.000000  143.276733  
AAACAATCTACTAGCA-1   0.000000    0.000000  
AAACAGAGCGACTCCT-1   0.000000  156.985870  
AAACAGTGTTCCTGGG-1   0.000000  287.046997  
AAACATTTCCCGGATT-1   0.000000  386.189880  
...        

# Split data

# Build classifier



In [4]:
# classify plaque or no plaque spots based gene expression
#----------------------------------------------------------------------
from sklearn.linear_model import LogisticRegression

In [9]:
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)

clf = LogisticRegression(random_state=0).fit(X, y)

/home/dburrows/anaconda3/envs/py_3916/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [16]:
X.shape, y

((150, 4),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))

In [12]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
clf.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
clf.predict_proba(X[:2, :])

array([[9.81815537e-01, 1.81844486e-02, 1.44032759e-08],
       [9.71757371e-01, 2.82425992e-02, 3.01211473e-08]])